const TYPES = {
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  LOADING: "LOADING",
  LOADED: "LOADED",
  LOGOUT: "LOGOUT",
  ADDCART: "ADDCART",
  GETCART: "GETCART",
  LOCATION: "LOCATION",
};

export { TYPES };
